sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rakubaku/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rakubaku/docker-react npm run test
